data:
  data_download: False
  data_path: '../data/'
  data_summary_path: '../data/summary/'
  data_summary_prefix: 'price_and_demand_'
  url_prefix: "https://aemo.com.au/aemo/data/nem/priceanddemand/PRICE_AND_DEMAND"
  start_year: 2000
  end_year: 2021
  states:
    - "NSW"
    - "VIC"
    - "QLD"
    - "SA"
    - "TAS"

